"""added few user attributes

Revision ID: 8e3aa735958d
Revises: 
Create Date: 2023-05-11 09:28:59.884237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3aa735958d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bankcode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tlname', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tlname')
        batch_op.drop_column('bankcode')

    # ### end Alembic commands ###
